name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-24.05
    - uses: cachix/cachix-action@v14
      with:
        name: kicad-template
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: ğŸ—ï¸ Build Template Board
      run: nix-build
    - name: ğŸ“¦ Upload result
      uses: actions/upload-artifact@v3
      with:
        name: template
        path: result/*